# site name
prefixName: loliloli.MOE
siteName: 幻想の小屋

logo:
  sakuraso: 幻想
  no: の
  shironeko: 小屋

# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/img/favicon.ico
avatar: img/avatar.png
url: https://www.loliloli.moe
description: “ 一切都是命运石之门的选择！ELPSYCONGROO！ ” 
cdn: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/

#局部加载 0关闭/1开启
pjax: 1
#公式渲染 0关闭/1开启
mathjax: 1

#首页提示语
notice: 欢迎来到幻想の小屋！

#加载动画
lazyloadImg: img/orange.progress-bar-stripe-loader.svg

#seo优化设定
seo:
  #网站简介
  description: 一切都是命运石之门的选择！ELPSYCONGROO！
  #关键词
  keywords: 小说,动漫,技术,Sakura

#首页菜单
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake }
  日常: { path: javascript:;, fa: fa-calendar faa-vertical, submenus: {
    番组: {path: /life/bangumi/, fa: fa-film faa-vertical },
    歌单: {path: /life/music/, fa: fa-headphones },
    图集: {path: /categories/photo/, fa: fa-photo }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    技术: {path: /categories/技术/, fa: fa-code }, 
    杂谈: {path: /categories/杂谈/, fa: fa-book },
    小说: {path: /categories/轻小说/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download },
    Mikutap: {path: https://loliloli.moe/mikutap/, fa: fa-music }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: {
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura }
  } }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  RSS: { path: /atom.xml, fa: fa-rss faa-vertical }
  #A1子号申请: {path: https://office.romeyer.live, fa: fa-windows faa-tada }

#页脚信息
# pagefooter: 这里是页脚信息

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10

# 背景图片 更好的修改
bg:
  # - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/webp/1.webp
  - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/webp/2.webp
  # - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/webp/3.webp
  - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDNimg/img/20200430211041.png
  # - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/webp/5.webp
  - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/webp/6.webp
  - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/webp/7.webp
  - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/webp/8.webp
  - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDNimg/img/20200430211348.png
  - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDNimg/img/61352183_p1_master1200.jpg
  - https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN/webp/11.webp
  
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash:
  - {url: /theme-sakura/, title: Sakura, desc: 本站 HEXO 主题, img: img/banner/screenshot.jpg }
  # - {url: /COVID-19, title: COVID-19MAP, desc: 新冠疫情地图, img: img/banner/V.png }
  - {url: /office365, title: office365 A1, desc: A1子号申请, img: img/banner/20200430211348.png }


# your site build time or founded date (建站日期）
siteBuildingTime: 2020-4-25

#页脚显示网站已运行时间
runtime: true

#social  url, img PC端配置
social:
  github: {url: https://github.com/RomEYer-AwELF, img: img/social/github.png }
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  #wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  #zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: mailto:romeyer@loliloli.moe, img: img/social/email.svg}
  #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1215651191&site=qq&menu=yes, img: img/social/qq.png }
  telegram: {url: https://t.me/romeyer_awelf, img: img/social/telegram.svg }
  
#social  url, img 移动端配置
msocial:
  #github: {url: https://github.com/RomEYer-AwELF, fa: fa-github, color: 333}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1215651191&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  switch: false

movies:
  switch: true
  url: https://od.loliloli.moe/%E7%A7%81%E4%BA%BA/Video/
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Shelter.m4v

aplayer:
  switch: true
  id: 2151143894
  server: netease
  type: playlist
  fixed: true 
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true
  listfolded: false
  

# Valine
valine: true
v_appId: sQ9C7Vuuba4TW3tsSwE8dEz0-gzGzoHsz # MOCEl4loIGAicV8DozU18vlL-MdYXbMMI 
v_appKey: 5DxGBtrJnxNXxKcx0EuVvV3C # In2WBWWv73WJKyQtPxyu72HO

# Waline
# Waline: true
# v_appId: sQ9C7Vuuba4TW3tsSwE8dEz0-gzGzoHsz # MOCEl4loIGAicV8DozU18vlL-MdYXbMMI 
# v_appKey: 5DxGBtrJnxNXxKcx0EuVvV3C # In2WBWWv73WJKyQtPxyu72HO
# serverURL: 

#42cloud 计数器
readcounts: true

#不蒜子计数器
busuanzi:
  switch: false

#每日一言
hitokoto: true

#全站灰白主题
gray: false

#Google Analytics
Google_Analytics:
  enable: true
  id: UA-168024025-1

style:
  enable: true

Google_AdSense:
  enable: true
  id: ca-pub-8545928941707976
  
skins: true

cnzz:
  enable: false
  id: cnzz_stat_icon_1278953952 
  
live2d:
  enable: true
  
#CSS和JS开始
libs:
  css:
   style: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.2/css/style.css
   lib: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/css/lib.min.css
   font: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/css/font.css
   insight: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/css/insight.css
   fancybox: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/css/jquery.fancybox.min.css
   #zoom: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/css/zoom.css
   sharejs: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/css/sharejs.css
   loli: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/css/loli.css
   googlefonts: https://cdn.jsdelivr.net/gh/xbclub/staticCDN@0.6/css/googlefont.css
   logo:
      enable: true 
      #logo: https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/logo.css
      logo_fonts: https://cdn.jsdelivr.net/gh/cungudafa/cdn/fonts/LOGO/logo.css
      logo: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@master/css/logo.css
      #logo_fonts: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@master/css/logo_font.css
  js:
   title: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/title.js
   jquery: https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
   lib: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/lib.min.js
   clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
   InsightSearch: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/InsightSearch.js
   fancybox: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/jquery.fancybox.min.js
   #zoom: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/zoom.min.js
   console: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/console.js
   smoove: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/jquery.smoove.min.js
   sakura: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/sakura-app.js
   #Valine: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/Valine.min.js
   Valine: https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
   botui: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/botui.js
   SmoothScroll: https://cdn.jsdelivr.net/gh/RomEYer-AwELF/CDN@2.1/js/SmoothScroll.min.js
